### ISSUE TITLE
Rebuild Config Compiler

### ISSUE THREAD

**Issue by tafseer-khan** [taubyte/go-project-schema#4]
rebuild [config-compiler](https://github.com/taubyte/config-compiler) and move here.

**Comment by samyfodil** [comment]
Config Compiler https://github.com/taubyte/config-compiler is a very complex implementation for what needs to be done.
The goal is to re-implement in a way where adding new features is easy. So we will do it in steps:
parse yaml -> convert to tree structure -> generate index -> clean up

**Comment by samyfodil** [comment]
Look at https://github.com/taubyte/tcc
